# Generated by Django 5.1.6 on 2025-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="record",
            name="province",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="record",
            name="country",
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name="record",
            name="email",
            field=models.CharField(max_length=255),
        ),
    ]
